### ISSUE TITLE
Directory.Build.props code analysis

### ISSUE THREAD

**Issue by gyozob** [zysharp/templates#1]
in the Directory.Build.props lately I use `<AnalysisLevel>latest-recommended</AnalysisLevel>` instead of `<EnableNETAnalyzers>true</EnableNETAnalyzers>`, EnableNETAnalyzers is [by default true if you target >=net5](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#code-quality-analysis) but I'm open for discussions on this subject if you have other thoughts :) (sorry for writing an issue here, I couldn't find a way to leave a comment on the file)

**Comment by flobernd** [comment]
Hey, thanks for the hint 🙂 I did not know about the new combined `AnalysisLevel` tag. I will probably use `latest-all` here as that probably matches the strict style of the used `.editorconfig` a little bit better.

The `EnableNETAnalyzers` sadly needs to stay as I always additionally target `netstandard2.0` to be compatible with older SDK version. It probably would not make a difference as the CI covers all targets, but this way it's probably a little bit more clear.

**Comment by gyozob** [comment]
for me the "all" was too strict, it reports things that are not that easy to globally handle (it also reported a performance issue with the logger) so I stick to the "recommended" for now :P I'm curious if you will agree with all the reported issues, for me it was just too much with TreatWarningsAsErrors on true :P

**Comment by flobernd** [comment]
Haha yeah I already noticed some checks that do not fit my style. In my `.editorconfig` I manage them all on a single place and disabled a few of them or changed severity to `suggestion`:

https://github.com/zysharp/templates/blob/0de384f17f9fc61a82fa02a6d7117aeb27597ad0/.editorconfig#L6-L13

Other than that, I usually prefer to review every single warning and selectively disable them in code on certain places.
